try {
    functionT();
} catch(error) {
    console.log(error)
}

try {
    anotherFn();
} catch {
    console.log('Prueba')
}